### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "Jacob",
    "password": "P@55word",
    "confPassword": "P@55word"
}

### Get User
GET http://localhost:3000/user
Content-Type: application/json

###
DELETE http://localhost:3000/pencatatan/11
Content-Type: application/json

### Get pencatatan sesuai dengan id_realisasinya
GET http://localhost:3000/pencatatan/2
Content-Type: application/json

###
PUT http://localhost:3000/pencatatan/12
Content-Type: application/json

{
    "no": 2,
    "kode": 534,
    "nominal": 25000,
    "total": 25000,
    "id_realisasi": 2
}


###
POST http://localhost:3000/pencatatan/create
Content-Type: application/json

{
    "no": 2,
    "kode": 533,
    "nominal": 2000,
    "total": 2000,
    "id_realisasi": 2
}

###
{
    "no": 1,
    "kode": 534,  //
    "nominal": 1500,
    "total": 1500,
    "id_realisasi": 2
}

###
GET http://localhost:3000/akun
Content-Type: application/json

###
GET http://localhost:3000/pencatatan
Content-Type: application/json

###
GET http://localhost:3000/realisasi
Content-Type: application/json